### ISSUE TITLE
[♻️ refactor] Replace default shadcn theme with custom theme

### ISSUE THREAD

**Issue by Fredkiss3** [Fredkiss3/zane-ops#50]
## What is the reason to do this refactor ?.

We want a customized theme instead of the default theme for our branding.

## Describe the work that needs to be done

You need to Copy the css variables for the theme inside of the `index.css` file, more context in the next section. 

## Additional context

Here is The link to the theme : https://ui.jln.dev/theme/zZ46KxUGKbXVSnsM

Here is the CSS of the theme : 
```css
/* inside of index.css */
@layer base {
    :root {
      --background: 164 62% 99%;
      --foreground: 164 67% 0%;
      --muted: 164 7% 89%;
      --muted-foreground: 164 0% 26%;
      --popover: 164 62% 99%;
      --popover-foreground: 164 67% 0%;
      --card: 164 62% 99%;
      --card-foreground: 164 67% 0%;
      --border: 164 9% 90%;
      --input: 164 9% 90%;
      --primary: 164 61% 70%;
      --primary-foreground: 164 61% 10%;
      --secondary: 201 94% 80%;
      --secondary-foreground: 201 94% 20%;
      --accent: 164 10% 85%;
      --accent-foreground: 164 10% 25%;
      --destructive: 11 98% 31%;
      --destructive-foreground: 11 98% 91%;
      --ring: 164 61% 70%;
      --radius: 0.5rem;
    }
  
    .dark {
      --background: 226 19% 13%;
      --foreground: 231 28% 73%;
      --muted: 226 12% 17%;
      --muted-foreground: 226 12% 67%;
      --popover: 226 19% 10%;
      --popover-foreground: 231 28% 83%;
      --card: 164 43% 2%;
      --card-foreground: 164 30% 100%;
      --border: 226 9% 18%;
      --input: 226 9% 21%;
      --primary: 164 61% 70%;
      --primary-foreground: 164 61% 10%;
      --secondary: 201 94% 80%;
      --secondary-foreground: 201 94% 20%;
      --accent: 164 18% 21%;
      --accent-foreground: 164 18% 81%;
      --destructive: 11 98% 56%;
      --destructive-foreground: 0 0% 100%;
      --ring: 164 61% 70%;
    }
  }
  
```

- [ ] Are you willing to make a PR for this ?
